spring:
  main:
    banner-mode: off

logging:
  level:
    root: info
    drrename: debug
    com:
      ulisesbocchio: warn
    drrename.kodi.nfo.NfoFileCollector: info
    drrename.kodi.nfo.NfoFileParser: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([%thread]) %yellow(%logger{20}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: none

app:
  ui:
    appTitle: "Dr.Rename"
    initialWidth: 600
    initialHeight: 600
    override-locale: de
  word-cnt: 3
  loop-delay-ms: 100
  reset-delay-ms: 500
  debug: true
  kodi:
    themoviedb:
      base-url: https://api.themoviedb.org/3
      include-adult: true
      number-of-max-suggestions: 5
      images:
        base-url: https://image.tmdb.org/t/p

