spring:
  main:
    web:
      application-type: none
    banner-mode: off

logging:
  level:
    com.github.drrename: debug
    com.kerner1000.drrename: debug
    drrename: debug

app:
  word-cnt: 3
  loop-delay-ms: 500
  debug: false

