spring:
  main:
    web:
      application-type: none

logging:
  level:
    com.github.drrename: debug
    com.kerner1000.drrename: debug

app.filecreator:
  word-cnt: 3
  debug: false
  loop-delay-ms: 500
  mainview:
    debug: false

