spring:
  main:
    banner-mode: off

logging:
  level:
    root: info
    drrename: info
    com:
      ulisesbocchio: warn
    drrename.kodi.nfo.NfoFileCollector: info
    drrename.kodi.nfo.NfoFileParser: info
    drrename.kodi.ui.control: info
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %magenta([%thread]) %yellow(%logger{20}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic

app:
  debug: false
  ui:
    appTitle: "Dr.Rename"
    initialWidth: 600
    initialHeight: 600
    imageHeight: 200
    override-locale: de
  word-cnt: 3
  loop-delay-ms: 300
  reset-delay-ms: 500
  kodi:
    ui:
      imageHeight: 265
      searchImageHeight: 100
    themoviedb:
      base-url: https://api.themoviedb.org/3
      include-adult: true
      number-of-max-suggestions: 8
      images:
        base-url: https://image.tmdb.org/t/p

