spring:
  main:
    web:
      application-type: none

logging:
  level:
    com.github.drrename: debug
    com.kerner1000.drrename: debug
    drrename: debug

app:
  filecreator:
    word-cnt: 3
    loop-delay-ms: 500
  mainview:
    debug: false

