spring:
  main:
    banner-mode: off

logging:
  level:
    root: info
    drkodi: info
#    drkodi.normalization: debug
#    drkodi.themoviedb: debug
#    drkodi.data.dynamic: debug
    com:
      ulisesbocchio: warn
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %magenta([%thread]) %yellow(%logger{20}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic

app:
  debug: false
  ui:
    appTitle: "Dr.Kodi"
    initialWidth: 600
    initialHeight: 600
    imageHeight: 200
#    override-locale: de
  word-cnt: 3
  loop-delay-ms: 300
  reset-delay-ms: 500
  kodi:
    ui:
      imageHeight: 265
      searchImageHeight: 100
    themoviedb:
      base-url: https://api.themoviedb.org/3
      include-adult: true
      number-of-max-suggestions: 8
      images:
        base-url: https://image.tmdb.org/t/p

  normalize:
    title:
      write:
        delete:
          - ","
          - "-"
          - "'"
          - "1080p"
          - "720p"
          - "DL"
          - "AC3"
          - "BluRay"
          - "x265"
          - "x264"
          - "imperium"
          - "german"
          - "fun"
        replace-with-space:
      compare:
        delete:
          - ","
          - "'"
          - ":"
          - "-"
        replace-with-space:
          - "."
          - "_"
      search:
        delete:
          - ","
          - "-"
          - "'"
          - "1080p"
          - "720p"
          - "DL"
          - "AC3"
          - "BluRay"
          - "x265"
          - "x264"
          - "imperium"
          - "german"
          - "fun"
        replace-with-space:
          - "."
          - "_"

