name: Build MacOS dmg

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  JAVA_VERSION: 17

jobs:
  build:
    name: Build .app
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Run maven
        run: mvn -B clean package -Pmacosx-x86_64 -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target/DrKodi/DrKodi.app
          path: DrKodi.app
          if-no-files-found: error
