name: Build Ubuntu

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  JAVA_VERSION: 17

jobs:
  build:
    name: Build Debian Package
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Run maven
        run: mvn -B clean package -Plinux -DskipTests